export const BannedWords = [
    'jerking',
    'jerked',
    'chinks',
    'gooks',
    'kike',
    'deepfake',
    'cybercrime',
    '1488',
    '2 girls 1 cup',
    'phallus',
    'molest',
    'Jack Idema',
    'scissoring',
    'pegging',
];
