export const fortunes: string[] = [
    'Reply hazy, try again',
    'Excellent Luck',
    'Good Luck',
    'Average Luck',
    'Bad Luck',
    'Good news will come to you by mail',
    'You will meet a dark handsome stranger',
    'Better not tell you now',
    'Outlook Good',
    'Very Bad Luck',
    'Godly Luck',
    'Ask again tomorrow',
    'It was going to happen, but by asking you\'ve altered the timeline',
    'It is inevitable',
    'You don\'t want to know.',
    'It will happen, but not in the way you think',
    'It won\'t happen, but you\'ll be better for it',
    'Hellishly Awful Luck',
];
